1.导入numpy 并简写为 np

In [1]:
import numpy as np

2.打印numpy的版本和配置说明

In [3]:
# numpy 的版本号
print(np.__version__)

# 配置说明
np.show_config()

1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

3.创建一个长度为10 的空向量

In [4]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.如何找到任何一个数组的内存大小

In [9]:
data = np.zeros((10,10))

In [10]:
print('%d bytes'%(data.size*data.itemsize))

800 bytes


5.如何从命令行得到numpy 中 add 函数的说明文档

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6.创建一个长度为 10 并且除了 第五个值为1 的空向量

In [12]:
data = np.zeros(10)
data[4] = 1
print(data)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.创建一个值域范围从10到49的向量

In [14]:
data7 = np.arange(10,50)
print(data7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8.反转向量

In [17]:
a = np.arange(50)
print(a)
data8 = a[::-1]
print(data8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9.创建一个 3*3 并且值为 0到8 的矩阵

In [23]:
ans9 = np.arange(9).reshape(3,3)
#array类型
print(ans9)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10.找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [29]:
ans10 = np.nonzero([1,2,0,0,4,0])
print(ans10)

(array([0, 1, 4], dtype=int64),)
